safe:           false
permalink:      /notes/:title/
pygments:       true
domain:	        http://flipside.org
name:           Flipside
description:    Flipside builds web-based tools for civil society organisations.
exclude:        ['node_modules', 'src', 'Gruntfile.js', 'package.json', 'Readme.md', 'bower.json']

# Image presets
# For more info: https://github.com/robwierzbowski/jekyll-image-tag
image:
  source: images
  output: images
  presets:
    article:
      height: 400
      width: 600
    list:
      height: 640
      width: 960
    thumb:
      attr:
        class: thumb
      height: 112
      width: 112
    polaroid:
      attr:
        height: 340
        width: 380
      height: 680
      width: 760  
